/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ejemplo.plugin.gradle.koltin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class EjemploPluginGradleKoltinPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("ejemplo-greeting") { task ->
            task.doLast {
                println("Hello from plugin 'ejemplo.plugin.gradle.koltin.greeting'")
            }
        }
    }
}
