/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ejemplo.plugin.gradle.koltin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'ejemplo.plugin.gradle.koltin.greeting' plugin.
 */
class EjemploPluginGradleKoltinPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("ejemplo.plugin.gradle.koltin.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("ejemplo-greeting"))
    }
}
